### ISSUE TITLE
Nested objects are not being indented correctly

### ISSUE THREAD

**Issue by torresjeff** [MinMiguelM/connector-utility#6]
Using the following YAML, this would yield an incorrect README.md
```
outputs:
      - name: entries
        arrayOf: object
        props:
          - name: id
            type: integer
            description: The unique id of the note
          - name: deal
            type: object
            description: The deal of the note
            props:
              - name: id
                type: integer
                description: ID of the note deal
              - name: name
                type: string
                description: Name of the note deal
```
